'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PPC_Manager_Tests.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!DOCTYPE tournament SYSTEM &quot;http://www.datenautomaten.nu/dtd/nuLiga/TournamentPortal.dtd&quot;&gt;
        '''&lt;tournament end-date=&quot;2012-09-09&quot; start-date=&quot;2012-09-08&quot; name=&quot;15. Turnier nach Schweizer Art &quot; tournament-id=&quot;Fp12HjV93pTyQlVex23%2FfGT919cb58I9&quot;&gt;
        '''	
        '''		&lt;competition start-date=&quot;2012-09-08 11:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;Mädchen U 13&quot; type=&quot;Einzel&quot;&gt;
        '''			&lt;players&gt;
        '''				
        '''			&lt;/players&gt;
        '''		&lt;/competition&gt;
        '''	
        '''		&lt;competition start-date=&quot;2012-09-08 11:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;Jungen [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Turnierteilnehmer() As String
            Get
                Return ResourceManager.GetString("Turnierteilnehmer", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
