'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PPC_Manager_Tests.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root xmlns:ppc=&quot;http://www.ttc-langensteinbach.de&quot; &gt;
        '''  &lt;competition start-date=&quot;2012-09-08 11:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;Mädchen U 13&quot; type=&quot;Einzel&quot;&gt;
        '''    &lt;players&gt;
        '''      &lt;player type=&quot;single&quot; id=&quot;PLAYER72&quot;&gt;
        '''        &lt;person licence-nr=&quot;53010&quot; club-federation-nickname=&quot;BaTTV&quot; club-name=&quot;TTC Langensteinbach e.V. &quot; sex=&quot;1&quot; ttr-match-count=&quot;102&quot; lastname=&quot;Ewald&quot; ttr=&quot;1294&quot; internal-nr=&quot;NU440049&quot; club-nr=&quot;428&quot; firstname=&quot;Florian&quot; birthyear=&quot;1981&quot;/&gt;
        '''      &lt;/player&gt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Competition() As String
            Get
                Return ResourceManager.GetString("Competition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;tournament end-date=&quot;2012-09-09&quot; start-date=&quot;2012-09-08&quot; name=&quot;15. Turnier nach Schweizer Art &quot; tournament-id=&quot;Fp12HjV93pTyQlVex23%2FfGT919cb58I9&quot;&gt;
        '''  &lt;competition start-date=&quot;2012-09-09 8:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;A-Klasse&quot; type=&quot;Einzel&quot; xmlns:ppc=&quot;http://www.ttc-langensteinbach.de&quot;&gt;
        '''    &lt;players&gt;
        '''      &lt;ppc:player id=&quot;PLAYER-1&quot;&gt;
        '''        &lt;person licence-nr=&quot;-1&quot; club-name=&quot;TTC Dietlingen&quot; sex=&quot;1&quot; ttr-match-count=&quot;0&quot; lastname=&quot;Krischer&quot; ttr=&quot;1573&quot; firstname=&quot;M [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property PPC_15_Anmeldungen() As String
            Get
                Return ResourceManager.GetString("PPC_15_Anmeldungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Ergebnisse&gt;
        '''  &lt;Klassement Name=&quot;A&quot;&gt;
        '''    &lt;Runde Nummer=&quot;1&quot;&gt;
        '''      &lt;Ergebnis VornameA=&quot;Hai Khanh&quot; VornameB=&quot;Remo&quot; SpielerA=&quot;Nguyen&quot; SpielerB=&quot;Nürnberg&quot; SätzeA=&quot;3&quot; SätzeB=&quot;0&quot; /&gt;
        '''      &lt;Ergebnis VornameA=&quot;Norman&quot; VornameB=&quot;Jörg&quot; SpielerA=&quot;Schreck&quot; SpielerB=&quot;Hirsch&quot; SätzeA=&quot;3&quot; SätzeB=&quot;1&quot; /&gt;
        '''      &lt;Ergebnis VornameA=&quot;Evgeni&quot; VornameB=&quot;Tim&quot; SpielerA=&quot;Stoyanov&quot; SpielerB=&quot;Welker&quot; SätzeA=&quot;3&quot; SätzeB=&quot;0&quot; /&gt;
        '''      &lt;Ergebnis VornameA=&quot;Kai&quot; VornameB=&quot;Tobias&quot; SpielerA=&quot;Kappe&quot;  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property PPC_15_Ergebnisse() As String
            Get
                Return ResourceManager.GetString("PPC_15_Ergebnisse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; 
        '''           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;         
        '''           targetNamespace=&quot;http://www.ttc-langensteinbach.de&quot;&gt;
        '''
        '''  &lt;xs:attribute name=&quot;satzdifferenz&quot; type=&quot;xs:boolean&quot;/&gt;
        '''  &lt;xs:attribute name=&quot;sonnebornberger&quot; type=&quot;xs:boolean&quot;/&gt;
        '''  &lt;xs:attribute name=&quot;anwesend&quot; type=&quot;xs:boolean&quot;/&gt;
        '''  &lt;xs:attribute name=&quot;abwesend&quot; type=&quot;xs:boolean&quot;/&gt;
        '''  &lt;xs:attribute name=&quot;bezahlt&quot; type=&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property SpeicherStandSchema() As String
            Get
                Return ResourceManager.GetString("SpeicherStandSchema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!DOCTYPE tournament SYSTEM &quot;http://www.datenautomaten.nu/dtd/nuLiga/TournamentPortal.dtd&quot;[]&gt;
        '''&lt;tournament end-date=&quot;2012-09-09&quot; start-date=&quot;2012-09-08&quot; name=&quot;15. Turnier nach Schweizer Art &quot; tournament-id=&quot;4MGSAgWpFNN%2FCGskx1WKbLUQRB6iFN7s&quot;&gt;
        '''  &lt;competition start-date=&quot;2012-09-08 11:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;Mädchen U 13&quot; type=&quot;Einzel&quot;&gt;
        '''    &lt;players&gt;
        '''      &lt;player type=&quot;single&quot; id=&quot;PLAYER1&quot;&gt;
        '''        &lt;person licence-nr=&quot;161858&quot; club-federation-nickname=&quot;BaTTV [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Testturnier() As String
            Get
                Return ResourceManager.GetString("Testturnier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!DOCTYPE tournament SYSTEM &quot;http://www.datenautomaten.nu/dtd/nuLiga/TournamentPortal.dtd&quot;[]&gt;
        '''&lt;tournament end-date=&quot;2012-09-09&quot; start-date=&quot;2012-09-08&quot; name=&quot;15. Turnier nach Schweizer Art &quot; tournament-id=&quot;Fp12HjV93pTyQlVex23%2FfGT919cb58I9&quot;&gt;
        '''  &lt;competition start-date=&quot;2012-09-08 11:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;Mädchen U 13&quot; type=&quot;Einzel&quot;&gt;
        '''    &lt;players&gt;&lt;/players&gt;
        '''  &lt;/competition&gt;
        '''  &lt;competition start-date=&quot;2012-09-08 11:00&quot; ttr-remarks=&quot;-&quot; age-group=&quot;Jungen U 1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Turnierteilnehmer() As String
            Get
                Return ResourceManager.GetString("Turnierteilnehmer", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
